app/params/models.py
from app import db
from pathlib import Path

# ! Parameter file mapping bottom of document !


class Base(db.Model):
    __abstract__ = True
    id = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    date_modified = db.Column(db.DateTime, default=db.func.current_timestamp(),
                              onupdate=db.func.current_timestamp())


def process_2b(lsb, msb):
    """Merge two bytes into bigger integer

    Args:
        lsb (int): least significant byte
        msb (int): most siginificant byte

    Returns:
        int: value up to 65535
    """
    return msb * 256 + lsb


def split_2b(num):
    """Split a 16 bit in 2x 8 bit

    Args:
        num (int): number below or equal to 65535

    Returns:
        list (2x string): split in bytes (string format)
    """
    lsb = num % 256
    msb = num // 256
    return [str(lsb), str(msb)]


class Params(Base):
    __tablename__ = "parameters_files"

    # Text
    csv_name = db.Column("csv_name", db.String(128), unique=True, nullable=False)
    short_name = db.Column("short_name", db.String(64), nullable=False)
    light_family = db.Column("light_family", db.String(32))

    # Bytes
    byte_128 = db.Column("byte_128", db.SmallInteger, nullable=False)
    byte_129 = db.Column("byte_129", db.SmallInteger, nullable=False)
    byte_130 = db.Column("byte_130", db.SmallInteger, nullable=False)
    byte_131 = db.Column("byte_131", db.SmallInteger, nullable=False)
    byte_132 = db.Column("byte_132", db.SmallInteger, nullable=False)
    byte_133 = db.Column("byte_133", db.SmallInteger, nullable=False)
    byte_134 = db.Column("byte_134", db.SmallInteger, nullable=False)
    byte_135 = db.Column("byte_135", db.SmallInteger, nullable=False)
    byte_136 = db.Column("byte_136", db.SmallInteger, default=0, nullable=False)
    byte_137_138 = db.Column("byte_137/138", db.SmallInteger, nullable=False)
    byte_139 = db.Column("byte_139", db.SmallInteger, nullable=False)
    byte_140 = db.Column("byte_140", db.SmallInteger, default=10, nullable=False)
    byte_141 = db.Column("byte_141", db.SmallInteger, default=130, nullable=False)
    byte_142 = db.Column("byte_142", db.SmallInteger, default=180, nullable=False)
    byte_143 = db.Column("byte_143", db.SmallInteger, default=156, nullable=False)
    byte_144 = db.Column("byte_144", db.SmallInteger, default=1, nullable=False)
    byte_145 = db.Column("byte_145", db.SmallInteger, nullable=False)
    byte_146 = db.Column("byte_146", db.SmallInteger, default=0, nullable=False)
    byte_147_148 = db.Column("byte_147/148", db.SmallInteger, nullable=False)
    byte_149_150 = db.Column("byte_149/150", db.SmallInteger, nullable=False)
    byte_151_152 = db.Column("byte_151/152", db.SmallInteger, nullable=False)
    byte_153_154 = db.Column("byte_153/154", db.SmallInteger, nullable=False)
    byte_155_156 = db.Column("byte_155/156", db.SmallInteger, nullable=False)
    byte_157_158 = db.Column("byte_157/158", db.SmallInteger, nullable=False)
    byte_159_160 = db.Column("byte_159/160", db.SmallInteger, nullable=False)
    byte_161_162 = db.Column("byte_161/162", db.SmallInteger, nullable=False)
    byte_163 = db.Column("byte_163", db.SmallInteger, nullable=False)
    byte_164 = db.Column("byte_164", db.SmallInteger, nullable=False)
    byte_165 = db.Column("byte_165", db.SmallInteger, nullable=False)
    byte_166 = db.Column("byte_166", db.SmallInteger, nullable=False)
    byte_167 = db.Column("byte_167", db.SmallInteger, nullable=False)
    byte_168 = db.Column("byte_168", db.SmallInteger, nullable=False)
    byte_169_170 = db.Column("byte_169/170", db.SmallInteger, nullable=False)
    byte_171 = db.Column("byte_171", db.SmallInteger, nullable=False)
    byte_172 = db.Column("byte_172", db.SmallInteger, nullable=False)
    byte_173 = db.Column("byte_173", db.SmallInteger, nullable=False)
    byte_174 = db.Column("byte_174", db.SmallInteger, nullable=False)
    byte_175_176 = db.Column("byte_175/176", db.SmallInteger, nullable=False)
    byte_177_178 = db.Column("byte_177/178", db.SmallInteger, nullable=False)
    byte_179_180 = db.Column("byte_179/180", db.SmallInteger, nullable=False)
    byte_181_182 = db.Column("byte_181/182", db.SmallInteger, nullable=False)
    byte_183_184 = db.Column("byte_183/184", db.SmallInteger, nullable=False)
    byte_185_186 = db.Column("byte_185/186", db.SmallInteger, nullable=False)
    byte_187_188 = db.Column("byte_187/188", db.SmallInteger, nullable=False)
    byte_189_190 = db.Column("byte_189/190", db.SmallInteger, nullable=False)
    byte_191_192 = db.Column("byte_191/192", db.SmallInteger, nullable=False)
    byte_193_194 = db.Column("byte_193/194", db.SmallInteger, nullable=False)
    byte_195_196 = db.Column("byte_195/196", db.SmallInteger, nullable=False)
    byte_197_198 = db.Column("byte_197/198", db.SmallInteger, nullable=False)
    byte_199_200 = db.Column("byte_199/200", db.SmallInteger, nullable=False)
    byte_201 = db.Column("byte_201", db.SmallInteger, default=18, nullable=False)
    byte_202_203 = db.Column("byte_202/203", db.SmallInteger, default=300, nullable=False)
    byte_204_205 = db.Column("byte_204/205", db.SmallInteger, default=610, nullable=False)
    byte_206 = db.Column("byte_206", db.SmallInteger, nullable=False)
    byte_207 = db.Column("byte_207", db.SmallInteger, nullable=False)
    byte_208_209 = db.Column("byte_208/209", db.SmallInteger, nullable=False)
    byte_210_211 = db.Column("byte_210/211", db.SmallInteger, nullable=False)
    byte_212 = db.Column("byte_212", db.SmallInteger, nullable=False)
    byte_213 = db.Column("byte_213", db.SmallInteger, nullable=False)
    byte_214 = db.Column("byte_214", db.SmallInteger, nullable=False)
    byte_215 = db.Column("byte_215", db.SmallInteger, nullable=False)

    @classmethod
    def upload_file(cls, path, delim=";", category=None):
        """
        Args:
            path (Path): Pathlib object from the correct filepath for this file you want to parse
            delim (str): Delimiter used in csv-file. Defaults to ";"
            category (str, optional): The category of lights in which these row falls. Defaults to None.

        Raises:
            AttributeError: File is not of correct structure, data must be on first line and must be 257 fields long
        """
        with open(path) as file:
            line_1 = file.readline()
            data = line_1.split(delim)
            if isinstance(data, list) and len(data) == 257:
                temp = cls()  # make object of class
                temp.csv_name = path.name
                temp.short_name = data.pop(0)
                if category:
                    temp.category = category
                byte_data_map = dict(zip(range(256), map(int, data)))
                temp._process_byte_data_map(byte_data_map)
                return temp
            else:
                raise AttributeError("Uploaded parameter file is not the correct length")

    def export_csv(self, delimiter=";", **kwargs):
        """
        Generate a csv file from the SQL parameters in the database

        Args:
            delimiter (str, optional): delimiter used for the csv file. Defaults to ";".
        Kwargs:
            filename: output filename - if not used, use csv_name inside the SQL DB
        """
        filename = kwargs.pop("filename", self.csv_name)
        data_map = self._generate_byte_data_map()
        vals = list(data_map.values())
        param = [self.short_name] + vals
        line = delimiter.join(param) + "\n"
        with open(Path("app", "temporary", filename), "w") as file:
            file.write(line)

    @property
    def flux_summ(self):
        fluxes = [self.byte_163, self.byte_164, self.byte_165, self.byte_166, self.byte_167, self.byte_168]
        if all([x == fluxes[0] for x in fluxes]):
            return fluxes[0]
        else:
            return "Vary"

    def _generate_byte_data_map(self):
        data_map = dict(zip(range(256), ["255"] * 256))
        data_map[128] = str(self.byte_128)
        data_map[129] = str(self.byte_129)
        data_map[130] = str(self.byte_130)
        data_map[131] = str(self.byte_131)
        data_map[132] = str(self.byte_132)
        data_map[133] = str(self.byte_133)
        data_map[134] = str(self.byte_134)
        data_map[135] = str(self.byte_135)
        data_map[136] = str(self.byte_136)
        data_map[137], data_map[138] = split_2b(self.byte_137_138)
        data_map[139] = str(self.byte_139)
        data_map[140] = str(self.byte_140)
        data_map[141] = str(self.byte_141)
        data_map[142] = str(self.byte_142)
        data_map[143] = str(self.byte_143)
        data_map[144] = str(self.byte_144)
        data_map[145] = str(self.byte_145)
        data_map[146] = str(self.byte_146)
        data_map[147], data_map[148] = split_2b(self.byte_147_148)
        data_map[149], data_map[150] = split_2b(self.byte_149_150)
        data_map[151], data_map[152] = split_2b(self.byte_151_152)
        data_map[153], data_map[154] = split_2b(self.byte_153_154)
        data_map[155], data_map[156] = split_2b(self.byte_155_156)
        data_map[157], data_map[158] = split_2b(self.byte_157_158)
        data_map[159], data_map[160] = split_2b(self.byte_159_160)
        data_map[161], data_map[162] = split_2b(self.byte_161_162)
        data_map[163] = str(self.byte_163)
        data_map[164] = str(self.byte_164)
        data_map[165] = str(self.byte_165)
        data_map[166] = str(self.byte_166)
        data_map[167] = str(self.byte_167)
        data_map[168] = str(self.byte_168)
        data_map[169], data_map[170] = split_2b(self.byte_169_170)
        data_map[171] = str(self.byte_171)
        data_map[172] = str(self.byte_172)
        data_map[173] = str(self.byte_173)
        data_map[174] = str(self.byte_174)
        data_map[175], data_map[176] = split_2b(self.byte_175_176)

app/params/forms.py
from flask_wtf import FlaskForm
from wtforms import MultipleFileField, StringField
from wtforms.validators import Regexp
# import email_validator


class UploadCsvForm(FlaskForm):
    files = MultipleFileField(label="File(s) to upload (only CSV allowed):")
    category = StringField(label="Light family:")
    # validators=[Regexp(".*\.csv$")]

app/params/controllers.py
from flask import Blueprint, request, render_template, \
    flash, session, redirect, url_for, send_file
from app.params.forms import UploadCsvForm
from app import db, login_required
from app.params.models import *
from app import app  # needed?
from pathlib import Path
import os

# TODO: (1) write FileStorage/stream backend in model

params = Blueprint('params', __name__, url_prefix='/params')


@params.route("/", methods=["GET", "POST"])
@login_required
def index():
    params_list = Params.query.order_by(Params.csv_name.asc())
    upload_form = UploadCsvForm()
    if upload_form.validate_on_submit():
        uploaded = upload_form.files.data
        for file in uploaded:
            if Params.query.filter_by(csv_name=file.filename).first():
                print("File '%s': name already taken" % file.filename)
                flash("File '%s': name already taken" % file.filename, category="warning")
                continue
            path = Path("app", "temporary", file.filename)
            temp = file.save(path)  # TODO: (1)
            try:
                param = Params.upload_file(path)
                param.light_family = upload_form.category.data
                db.session.add(param)
                flash("File '%s': added to database" % param.csv_name, category="success")
            except AttributeError:
                print("File '%s': invalid data type" % file.filename)
                flash("File '%s': invalid data type" % file.filename, category="error")
            finally:
                os.remove(path)
        db.session.commit()
        params_list = Params.query.order_by(Params.csv_name.asc())
    return render_template("params/index.html", params=params_list, upload_form=upload_form)


@params.route("/<param_id>", methods=["GET", "POST"])
@login_required
def detail(param_id):
    param = Params.query.filter_by(id=param_id).first()
    # TODO: implement next/prev param
    order_id = [x.id for x in Params.query.order_by(Params.csv_name.asc())]
    pos = order_id.index(int(param_id))
    try:
        prev_id = order_id[pos - 1]
        next_id = order_id[(pos + 1) if pos < (len(order_id) - 1) else 0]
    except IndexError:
        flash("Something went wrong determining next parameter in sequence", "error")
    if request.method == "POST":
        if param.query.filter_by(csv_name=request.form["csv_name"]).first():
            param.update_with_dict(request.form)
            flash("File '{}' updated in database".format(request.form['csv_name']), category="info")
        else:
            temp = Params()
            temp.update_with_dict(request.form)
            db.session.add(temp)
            flash("File '{}' added to database".format(request.form['csv_name']), category="success")
            param = temp
        db.session.commit()
    return render_template("params/detail.html", param=param, id_prev_next=[prev_id, next_id])


@params.route("delete/<param_id>")
@login_required
def delete(param_id):
    param = Params.query.filter_by(id=param_id).first()
    db.session.delete(param)
    db.session.commit()
    flash("File '%s' delete from database" % param.csv_name, category="info")
    return redirect(url_for("params.index"))


@params.route("export/<param_id>")
@login_required
def export(param_id):
    param = Params.query.filter_by(id=param_id).first()
    param.export_csv()
    return send_file(Path("temporary", param.csv_name), as_attachment=True, mimetype="text/csv", attachment_filename=param.csv_name)

app/templates/params/detail.html
{% extends 'base.html' %}

{% block title %}
Param with id {{ param.id }}
{% endblock %}

{% block cont_main %}
<div class="row">
    <div class="col-2 px-3 action-bar mt-1">
        <div class="row gx-1">
            <div class="col-lg-6 my-1"><a href="{{ url_for('params.index') }}" class="button-adb detail-button h-100">DB
                    Home</a></div>
            <div class="col-lg-6 my-1"><a href="{{ url_for('params.export', param_id = param.id) }}"
                    class="button-adb detail-button h-100">Export
                    CSV</a></div>
        </div>
        <div class="row gx-1">
            <div class="col-lg-6 my-1"><button id="save_db" class="button-adb detail-button h-100">Save</button></div>
            <div class="col-lg-6 my-1"><a href="{{ url_for('params.detail', param_id = id_prev_next.1)}}"
                    class="button-adb detail-button h-100">Param
                    Next</a></div>
        </div>
        <div class="row gx-1">
            <div class="col-lg-6 my-1"><a href="{{ url_for('params.delete', param_id = param.id) }}"
                    class="button-adb detail-button h-100">Delete</a></div>
            <div class="col-lg-6 my-1"><a href="{{ url_for('params.detail', param_id = id_prev_next.0)}}"
                    class="button-adb detail-button h-100">Param
                    Prev</a></div>
        </div>
        <div class="row my-1 gx-1">
            <button id="dc-color" class="button-adb detail-button">Default dimming curve color</button>
        </div>
        <div class="row my-1 gx-1">
            <button id="dc-white" class="button-adb detail-button">Default dimming curve white</button>
        </div>
        <div class="row gx-1">
            <div class="col-lg-6 my-1"><button id="set-flux" class="button-adb detail-button">Set Flux</button></div>
            <div class="col-lg-6 my-1"><input id="flux-input" class="form-control side-bar-input"></div>
        </div>
        <div class="row my-1 gx-1">
            <button id="prog_today" class="button-adb detail-button">Programming date to today</button>
        </div>
        <div class="row my-1 gx-1">
            <button id="release_today" class="button-adb detail-button">Release date to today</button>
        </div>
        {% include 'flashes.html' %}
    </div> <!-- 2nd row-->


    <div class="col-10">
        <form id="param-form" method="post" action="{{ url_for('params.detail', param_id = param.id) }}">
            <div class="row">
                <!-- !unprotected with CSRF, not critical for localhost -->
                {% with p_dict = param.export_dict() %}
                <div class="col-6">
                    <div id="csv_name" class="detail-field m-1 p-1 param-meta">
                        <b class="mx-2 align-middle">CSV name</b><input type="text" name="csv_name"
                            class="float-end mx-2 form-control field-input" size="60" value="{{ param.csv_name }}">
                    </div>
                </div>
                <div class="col-3">
                    <div id="short_name" class="detail-field m-1 p-1 param-meta">
                        <b class="mx-2 align-middle">Short name</b><input type="text" name="short_name"
                            class="float-end mx-2 form-control field-input" size="20" value="{{ param.short_name }}">
                    </div>
                </div>
                <div class="col-3">
                    <div id="light_family" class="detail-field m-1 p-1 param-meta">
                        <b class="mx-2 align-middle">Light Family</b><input type="text" name="light_family"
                            class="float-end mx-2 form-control field-input" size="5" value="{{ param.light_family }}">
                    </div>
                </div>
                {% for k, v in p_dict.items() %}
                <div class="col-3">
                    <div class="detail-field {{ v.1 }} m-1 p-1">
                        <b class="mx-2 align-middle">{{ k }}</b><input type="text" id="{{ k }}" name="{{ k }}"
                            class="float-end mx-2 form-control field-input" size="5" value="{{ v.0 }}">
                    </div>
                </div> <!-- col-3 -->
                {% endfor %}
                {% endwith %}
            </div> <!-- row -->
        </form>
    </div> <!-- col-10 -->
</div> <!-- row -->
{% endblock %}

{% block footer_script %}
<script src="{{ url_for('static', filename='js/param_detail.js' )}}"></script>
{% endblock %}

app/templates/params/flashes.html
<div class="row">
    <!-- flashes -->
    <div class="col-12">
        {% with messages = get_flashed_messages(with_categories = true) %}
        {% if messages %}
        {% for message in messages %}
        {% if message.0 == "success" %}
        <div class="row my-2 bg-success message-popup py-1">
            <b>{{ message.1 }}</b>
        </div> <!-- row -->
        {% endif %}
        <!-- success if -->
        {% if message.0 == "info" %}
        <div class="row my-2 bg-info message-popup py-1">
            <b>{{ message.1 }}</b>
        </div> <!-- row -->
        {% endif %}
        <!-- info if -->
        {% if message.0 == "warning" %}
        <div class="row my-2 bg-warning message-popup py-1">
            <b>{{ message.1 }}</b>
        </div> <!-- row -->
        {% endif %}
        <!-- warning if -->
        {% if message.0 == "error" %}
        <div class="row my-2 bg-danger message-popup py-1">
            <b>{{ message.1 }}</b>
        </div> <!-- row -->
        {% endif %}
        <!-- error if -->
        {% endfor %}
        <!-- message loop -->
        {% endif %}
        <!-- messages if -->
        {% endwith %}
        <!-- with messages -->
    </div> <!-- col-12 -->
</div> <!-- flashes -->

app/templates/params/index.html
{% extends 'base.html' %}

{% block meta %}

{% endblock %}

{% block title %}
Params - Home
{% endblock %}

{% block cont_main %}
{% include 'flashes.html' %}

<div class="row ps-2 my-2">
    <div class="col-4 message-popup py-1" id="file-submit">
        <form method="post" action="{{ url_for('params.index') }}" enctype="multipart/form-data">
            <span class="d-inline-block">
                {{ upload_form.csrf_token }}
                {{ upload_form.files.label }}
                {{ upload_form.files }}<br>
            </span>
            <span class="d-inline-block pt-2 w-100">
                {{ upload_form.category.label }}
                {{ upload_form.category(size=32) }}
                <input class="float-end" type="submit" name="submit" value="Submit">
            </span>
        </form>
    </div> <!-- col -->
</div> <!-- row -->

<div class="row my-2">
    <div class="col">
        <table class="table table-sm table-bordered">
            <tr class="tr-header">
                <th rowspan="2">CSV name</th>
                <th>Current</th> <!-- byte_137/138-->
                <th>Forw Volt</th> <!-- byte_139 or byte_210/211-->
                <th># of LEDs</th> <!-- byte_145 -->
                <th>LED Rev</th> <!-- byte_146 -->
                <th>DC 1.4</th> <!-- byte_147_148 -->
                <th>DC 2.8</th> <!-- byte_149_150 -->
                <th>DC 3.4</th> <!-- byte_151_152 -->
                <th>DC 4.1</th> <!-- byte_153_154 -->
                <th>DC 4.8</th> <!-- byte_155_156 -->
                <th>DC 5.2</th> <!-- byte_157_158 -->
                <th>DC 5.5</th> <!-- byte_159_160 -->
                <th>DC 6.6</th> <!-- byte_161_162 -->
                <th>Flux</th> <!-- bytes... -->
                <th>Lin Dim</th> <!-- byte_202_203 -->
                <th>Dim Freq</th> <!-- byte_204_205 -->
                <th>Dual Mon</th> <!-- byte_215 -->
                <th rowspan="3">Detail View</th>
            </tr>
            <tr class="tr-header">
                <th>(mA)</th>
                <th>(V)</th>
                <th>/</th>
                <th>/</th>
                <th>(mA)</th>
                <th>(mA)</th>
                <th>(mA)</th>
                <th>(mA)</th>
                <th>(mA)</th>
                <th>(mA)</th>
                <th>(mA)</th>
                <th>(mA)</th>
                <th>(%)</th>
                <th>(Hz)</th>
                <th>(mA)</th>
                <th>/</th>
            </tr>
            <tr id="search-header" class="tr-header">
                <th><input class="form-control" id="csv-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="curr-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="vf-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="num-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="rev-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="dc14-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="dc28-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="dc34-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="dc41-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="dc48-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="dc52-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="dc55-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="dc66-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="flux-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="lindim-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="freq-search" value="" placeholder="filter"></th>
                <th><input class="form-control" id="dualmon-search" value="" placeholder="filter"></th>
            </tr>
            {% for param in params %}
            <tr class="table-hover tr-data">
                <td style="text-align: left;">{{ param.csv_name }}</td>
                <td>{{ param.byte_137_138 }}</td>
                {% if param.byte_139 == 255 %}
                <td>{{ param.byte_210_211 / 100 }}</td>
                {% else %}
                <td>{{ param.byte_139 / 10 }}</td>
                {% endif %}
                <td>{{ param.byte_145 }}</td>
                <td>{{ param.byte_146 }}</td>
                <td>{{ param.byte_147_148 }}</td>
                <td>{{ param.byte_149_150 }}</td>
                <td>{{ param.byte_151_152 }}</td>
                <td>{{ param.byte_153_154 }}</td>
                <td>{{ param.byte_155_156 }}</td>
                <td>{{ param.byte_157_158 }}</td>
                <td>{{ param.byte_159_160 }}</td>
                <td>{{ param.byte_161_162 }}</td>
                <td>{{ param.flux_summ }}</td>
                <td>{{ param.byte_202_203 }}</td>
                <td>{{ param.byte_204_205 }}</td>
                <td>{{ param.byte_215 }}</td>
                <td><a class="button-adb detail-link"
                        href="{{ url_for('params.detail', param_id = param.id)  }}">Detail</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div> <!-- col-->
</div> <!-- row -->
{% endblock %}

{% block footer_script %}
<script src="{{ url_for('static', filename='js/param_index.js' ) }}"></script>
{% endblock %}