app/magnetics/controllers.py
from flask import Blueprint, request, render_template, \
    flash, g, session, redirect, url_for
from app import db, login_required, app
import pandas as pd
from pathlib import Path
from .forms import ConfigurationForm
from flask import json
from .support_functions import *

# used in app/__init__.py
magnetics = Blueprint('magnetics', __name__, url_prefix='/magnetics')

# -- factors dataframes
PERM_DC = pd.read_csv(Path(app.config["STATIC_FOLDER"], "info", "perm_dc.csv"))
CORE_LOSS = pd.read_csv(Path(app.config["STATIC_FOLDER"], "info", "core_loss.csv"))
NORM_MAGN = pd.read_csv(Path(app.config["STATIC_FOLDER"], "info", "normal_magn.csv"))
PERM_FREQ = pd.read_csv(Path(app.config["STATIC_FOLDER"], "info", "perm_freq.csv"))
PERM_TEMP = pd.read_csv(Path(app.config["STATIC_FOLDER"], "info", "perm_temp.csv"))
INFO_DICT = {"perm_dc": PERM_DC, "core_loss": CORE_LOSS, "norm_magn": NORM_MAGN, "perm_freq": PERM_FREQ, "perm_temp": PERM_TEMP}
MATERIAL_LIST = list(zip(["_".join(x.split(" ")) for x in PERM_DC.material.unique()], PERM_DC.material.unique()))
MATERIAL_SEARCH = dict(MATERIAL_LIST)
MATERIAL_SEARCH_INVERSE = dict(list(zip(PERM_DC.material.unique(), ["_".join(x.split(" ")) for x in PERM_DC.material.unique()])))


@magnetics.route("/")
@login_required
def index():
    form = ConfigurationForm()
    form.material.choices = MATERIAL_LIST
    return render_template("magnetics/index.html", form=form)


@magnetics.route("/set_mat/<mat>")
@login_required
def set_mat(mat):
    material = MATERIAL_SEARCH[mat]
    available_options = list(PERM_DC[PERM_DC.material == material].perm.unique())
    return json.dumps(list(map(str, available_options)))


@magnetics.route("/get_factors/<mat>/<perm>")
@login_required
def get_factors(mat, perm):
    factors_dict = dict()
    mat = MATERIAL_SEARCH[mat]
    factors_dict = get_specific_factors(mat, perm, ["a", "b", "c"], factors_dict, PERM_DC, "perm_dc")
    factors_dict = get_specific_factors(mat, perm, ["a", "b", "c"], factors_dict, CORE_LOSS, "core_loss")
    factors_dict = get_specific_factors(mat, perm, ["a", "b", "c", "d", "e", "x"], factors_dict, NORM_MAGN, "norm_magn")
    factors_dict = get_specific_factors(mat, perm, ["a", "b", "c", "d", "e"], factors_dict, PERM_FREQ, "perm_freq")
    factors_dict = get_specific_factors(mat, perm, ["a", "b", "c", "d", "e"], factors_dict, PERM_TEMP, "perm_temp")
    return json.dumps(factors_dict)

app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap/CSS/JS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossorigin="anonymous"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap_extended.css') }}">
        <script src="{{ url_for('static', filename='js/base.js' )}}"></script>

        {% block meta %}

        {% endblock %}

        <!-- Addition head -->
        <title>{% block title %} {% endblock %}</title>
        <link rel="shortcut icon" href="{{url_for('static', filename='img/favicon.ico')}}">
    </head>
    <body class="vh-100">
        <!-- !HEADER/NAV -->
        <nav class="px-5 nav sticky-top justify-content-start nav-base">
            <a class="h-100 nav-link p-0 nav-item" href="{{ url_for('index') }}"><img class="h-100"
                    src="{{ url_for('static', filename='img/ADBSG_logo_resized.gif') }}"></a>
            <a class="nav-link nav-item" href="{{ url_for('params.index') }}">Parameters</a>
            <a class="nav-link nav-item" href="{{ url_for('dimming.index') }}">Dimming</a>
            <a class="nav-link nav-item" href="{{ url_for('magnetics.index') }}">Magnetics</a>
            {% if session._user_id%}
            <a class="nav-link nav-item ms-auto" href="{{ url_for('logout') }}">Logout</a>
            {% else %}
            <a class="nav-link nav-item ms-auto" href="{{ url_for('register')}}">Register</a>
            <a class="nav-link nav-item" href="{{ url_for('login') }}">Login</a>
            {% endif %}
        </nav>
        <div class="container-fluid px-5 d-flex flex-column" style="height: 95vh;">
            {% if False %}
            <div>
                <!-- !messages for debug and session information -->
                <b>Flashes:</b><br>
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <ul class="flashes">
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% endwith %}
                <b>Session:</b><br>
                <ul class="session">
                    {% for k, v in session.items() %}
                    <li>{{ k }}: {{ v }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            {% block cont_main %}

            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
            integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
            integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
            crossorigin="anonymous"></script>
        {% block footer_script %}

        {% endblock %}
        <!-- <footer class="footer fixed-bottom d-flex justify-content-end">
            <div class="align-self-center">&#x00A9; ADBSG - KVS</div>
        </footer> -->
    </body>
</html>

app/templates/flashes.html
<div class="row">
    <!-- flashes -->
    <div class="col-12">
        {% with messages = get_flashed_messages(with_categories = true) %}
        {% if messages %}
        {% for message in messages %}
        {% if message.0 == "success" %}
        <div class="row my-2 bg-success message-popup py-1">
            <b>{{ message.1 }} <img class="hide-button" src="{{ url_for('static', filename = 'img/close_button.png' )}}"
                    style="width: 1rem; height: 1rem;"></b>
        </div> <!-- row -->
        {% endif %}
        <!-- success if -->
        {% if message.0 == "info" %}
        <div class="row my-2 bg-info message-popup py-1">
            <b>{{ message.1 }} <img class="hide-button" src="{{ url_for('static', filename = 'img/close_button.png' )}}"
                    style="width: 1rem; height: 1rem;"></b>
        </div> <!-- row -->
        {% endif %}
        <!-- info if -->
        {% if message.0 == "warning" %}
        <div class="row my-2 bg-warning message-popup py-1">
            <b>{{ message.1 }} <img class="hide-button" src="{{ url_for('static', filename = 'img/close_button.png' )}}"
                    style="width: 1rem; height: 1rem;"></b>
        </div> <!-- row -->
        {% endif %}
        <!-- warning if -->
        {% if message.0 == "error" %}
        <div class="row my-2 bg-danger message-popup py-1">
            <b>{{ message.1 }} <img class="hide-button" src="{{ url_for('static', filename = 'img/close_button.png' )}}"
                    style="width: 1rem; height: 1rem;"></b>
        </div> <!-- row -->
        {% endif %}
        <!-- error if -->
        {% endfor %}
        <!-- message loop -->
        {% endif %}
        <!-- messages if -->
        {% endwith %}
        <!-- with messages -->
    </div> <!-- col-12 -->
</div> <!-- flashes -->
<script>
    $(".hide-button").on("click", function () {
        // console.log($(this));
        $(this).parent().parent().hide();
    })
</script>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
Homepage
{% endblock %}

{% block cont_main %}
<div class="row">
    <div class="col-4">
        <h2 class="mt-3" style="color: var(--adbblue);">Contents</h2>
        <div class="list-group">
            <a class="list-group-item" href="{{ url_for('params.index') }}">
                <div class="d-flex w-100 justify-content-between">
                    <h5>Parameters</h5>
                    <small>LED configuration files</small>
                </div>
                <p>Parameter file database that enables configuration, alteration and generation of parameter files.
                </p>
            </a>
        </div>
        <div class="list-group">
            <a class="list-group-item" href="{{ url_for('dimming.index') }}">
                <div class="d-flex w-100 justify-content-between">
                    <h5>Dimming</h5>
                    <small>Dimming curves & plotting</small>
                </div>
                <p>Dimming curves database that also provide a way of plotting.
                </p>
            </a>
        </div>
        <div class="list-group">
            <a class="list-group-item" href="{{ url_for('magnetics.index') }}">
                <div class="d-flex w-100 justify-content-between">
                    <h5>Magnetics</h5>
                    <small>Powder core calculations</small>
                </div>
                <p>Powder core calculation tool with magnetics data.
                </p>
            </a>
        </div>
    </div>
</div>

{% endblock %}